---
title: "p8105_hw6_lc3391"
author: "Lu Chen"
date: "11/24/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
library(modelr)
library(mgcv)
library(p8105.datasets)

```
# Problem 1
```{r, message=FALSE}
#importing and cleaning data
birthwgt = read_csv("./data/birthweight.csv", na="") %>% 
  mutate(
    babysex = factor(babysex),
    frace = factor(frace),
    mrace = factor(mrace),
    malform = factor(malform)
  )

#is.na(birthwgt) #there is no missing value in the dataset

#build a model A
fit = lm(bwt ~ babysex + delwt + fincome + gaweeks + smoken, data = birthwgt)
# after scanning variables in the dataset, I think the sex of baby, mother's smoking status and amount during pregancy, mother's weight at delivery, baby's gestational age in weeks could all affect the birthweight of newborn.

fit %>% broom::tidy()

  birthwgt %>% 
  modelr::add_residuals(fit) %>% 
  modelr::add_predictions(fit) %>% 
  ggplot(aes(x = resid, y = pred)) + 
  geom_violin()

# Model B
fit2 = lm(bwt ~ blength + gaweeks, data = birthwgt) 

fit2 %>% broom::tidy()

birthwgt %>% 
  modelr::add_residuals(fit2) %>% 
  modelr::add_predictions(fit2) %>% 
  ggplot(aes(x = resid, y = pred)) + 
  geom_violin()

# Model C

fit3 = lm(bwt ~ bhead + blength + babysex + bhead*babysex + bhead*blength + blength*babysex + bhead*blength*babysex, data = birthwgt)

fit3 %>% broom::tidy()

birthwgt %>% 
  modelr::add_residuals(fit3) %>% 
  modelr::add_predictions(fit3) %>% 
  ggplot(aes(x = resid, y = pred)) + 
  geom_violin()

#making comparsion

cv_birthwgt = 
  crossv_mc(birthwgt, 100)

cv_birthwgt =
  cv_birthwgt %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))

cv_birthwgt = 
  cv_birthwgt %>% 
  mutate(model_a  = map(train, ~lm(bwt ~ babysex + delwt + fincome + gaweeks + smoken, data = .x)),
         model_b  = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
         model_c  = map(train, ~lm(bwt ~ bhead + blength + babysex + bhead*babysex + bhead*blength + blength*babysex + bhead*blength*babysex, data = .x))) %>% 
  mutate(rmse_modela = map2_dbl(model_a, test, ~rmse(model = .x, data = .y)),
         rmse_modelb = map2_dbl(model_b, test, ~rmse(model = .x, data = .y)),
         rmse_modelc = map2_dbl(model_c, test, ~rmse(model = .x, data = .y)))

cv_birthwgt %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()

# from the plot, we see that the model c, with includes the head circumference, length, sex, and all interactions (including the three-way interaction) between these, fits the best (with lowest rmse value)

```

## Problem 2
```{r}
#data importing

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

set.seed(1)

weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::glance)) %>% 
  select(-strap, -models) %>% 
  unnest(results) %>% 
  select(.id,r.squared) %>% 
  ggplot(aes(x = r.squared)) +
  geom_density() +
  theme_bw()

# the distribution of  estimated r-square is about normal.

weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(-strap, -models) %>% 
  unnest(results) %>% 
  select(.id,term,estimate) %>% 
  pivot_wider(names_from = term, values_from = estimate) %>% 
  mutate(log_beta0_beta1 = log(`(Intercept)`*tmin, base = exp(1))) %>% 
  ggplot(aes(x = log_beta0_beta1)) +
  geom_density() +
  theme_bw()

# the distribution of log(beta0*beta1) is about normal.

# 95% Confidence Interval

rsquared = 
weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::glance)) %>% 
  select(-strap, -models) %>% 
  unnest(results) %>% 
  select(.id,r.squared)
  
quantile(rsquared$r.squared, probs= c(0.025,0.975))

log_f = 
  weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(-strap, -models) %>% 
  unnest(results) %>% 
  select(.id,term,estimate) %>% 
  pivot_wider(names_from = term, values_from = estimate) %>% 
  mutate(log_beta0_beta1 = log(`(Intercept)`*tmin, base = exp(1)))

quantile(log_f$log_beta0_beta1, probs= c(0.025,0.975))


```

